/**
 * 매칭 테스트용 5명 더미(프라이버시: 이메일 없음, `prisma/seed.js` 시드와 동일 설문 구성).
 */

const surveySimilarPair = () => ({
  energy: 2,
  weekend: 3,
  pattern: 1,
  trend: 2,
  alcohol: '가끔',
  smoking: '비흡연',
  tattoo: '없음',
  contact: 4,
  meeting: 4,
  planning: 1,
  affection: 4,
  date_expense: 3,
  friends: 4,
  jealousy: 2,
  skinship_speed: 2,
  skinship_limit: '단계적으로',
  date_drinking: 2,
  politics: 3,
  religion_type: '없음',
  religion_intensity: null,
  marriage_view: 3,
  meeting_seriousness: 4,
  job_view: 4,
  spending: 3,
  conflict: 2,
  empathy: 5,
  honesty: 5,
  trust: 5,
  pref_cc: '비슷하면 좋음',
  pref_smoking: '비흡연',
  pref_tattoo: '선호',
  pref_religion: '비슷하면 좋음',
});

const surveyHardFilterA = () => ({
  energy: 5,
  weekend: 5,
  pattern: 5,
  trend: 5,
  alcohol: '자주',
  smoking: '흡연',
  tattoo: '있음',
  contact: 5,
  meeting: 5,
  planning: 5,
  affection: 5,
  date_expense: 5,
  friends: 5,
  jealousy: 5,
  skinship_speed: 5,
  skinship_limit: '빠르게',
  date_drinking: 5,
  politics: 5,
  religion_type: '기독교',
  religion_intensity: 5,
  marriage_view: 5,
  meeting_seriousness: 5,
  job_view: 5,
  spending: 5,
  conflict: 1,
  empathy: 2,
  honesty: 3,
  trust: 3,
  pref_cc: '매우 잦게',
  pref_smoking: '비흡연만',
  pref_tattoo: '없음만',
  pref_religion: '무교만',
});

const surveyHardFilterB = () => ({
  energy: 1,
  weekend: 1,
  pattern: 1,
  trend: 1,
  alcohol: '전혀 안 함',
  smoking: '비흡연',
  tattoo: '없음',
  contact: 1,
  meeting: 1,
  planning: 1,
  affection: 1,
  date_expense: 1,
  friends: 1,
  jealousy: 1,
  skinship_speed: 1,
  skinship_limit: '매우 천천히',
  date_drinking: 1,
  politics: 1,
  religion_type: '없음',
  religion_intensity: null,
  marriage_view: 1,
  meeting_seriousness: 1,
  job_view: 1,
  spending: 1,
  conflict: 5,
  empathy: 5,
  honesty: 5,
  trust: 5,
  pref_cc: '최소한으로',
  pref_smoking: '흡연만',
  pref_tattoo: '있음만',
  pref_religion: '종교 있음만',
});

const surveyRandomMix = () => ({
  energy: 4,
  weekend: 1,
  pattern: 3,
  trend: 5,
  alcohol: '월 1회',
  smoking: '전자담배만',
  tattoo: '작은 것만',
  contact: 3,
  meeting: 2,
  planning: 4,
  affection: 2,
  date_expense: 4,
  friends: 3,
  jealousy: 4,
  skinship_speed: 3,
  skinship_limit: '상의 후',
  date_drinking: 2,
  politics: 2,
  religion_type: '불교',
  religion_intensity: 3,
  marriage_view: 4,
  meeting_seriousness: 2,
  job_view: 2,
  spending: 5,
  conflict: 3,
  empathy: 3,
  honesty: 4,
  trust: 2,
  pref_cc: '상대에 맞춤',
  pref_smoking: '상관없음',
  pref_tattoo: '상관없음',
  pref_religion: '상관없음',
});

function getDummyMatchUsers() {
  return [
    {
      id: 'dummy-match-01',
      mbti: 'INTJ',
      surveyData: surveySimilarPair(),
    },
    {
      id: 'dummy-match-02',
      mbti: 'ENFP',
      surveyData: {
        ...surveySimilarPair(),
        affection: 3,
        trust: 4,
      },
    },
    {
      id: 'dummy-hardfilter-03',
      mbti: 'ESTP',
      surveyData: surveyHardFilterA(),
    },
    {
      id: 'dummy-hardfilter-04',
      mbti: 'ISFJ',
      surveyData: surveyHardFilterB(),
    },
    {
      id: 'dummy-random-05',
      mbti: 'INFP',
      surveyData: surveyRandomMix(),
    },
  ];
}

module.exports = { getDummyMatchUsers };
